apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ quarkus.namespace }}-gateway
  namespace: {{ quarkus.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "{{ route.results[0]['result']['spec']['host'] }}"