apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kogito-istio
  namespace: {{ quarkus.namespace }}
spec:
  host: kogito-istio
  subsets:
  - name: v1
    labels:
      version: v1