apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ quarkus.namespace }}
  namespace: {{ quarkus.control_plane_namespace }}
spec:
  path: /
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: http2