apiVersion: v1
kind: Service
metadata:
  name: kogito-istio
  namespace: 
  labels:
    app: kogito-istio
    service: kogito-istio
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: kogito-istio
